#!/bin/bash

FILE_PATH="/usr/lib/node_modules/lamassu-server/lib/plugins/wallet/geth/base.js"

# Ensure the file exists before attempting to modify it
if [ ! -f "$FILE_PATH" ]; then
  echo "Error: File not found: $FILE_PATH"
  exit 1
fi

# Use sed to replace the maxPriorityFeePerGas line
sed -i "s/const maxPriorityFeePerGas = new BN(web3.utils.toWei('2.5', 'gwei')) \/\/ web3 default value/const maxPriorityFeePerGas = new BN(web3.utils.toWei('1.0', 'gwei')) \/\/ web3 default value/" "$FILE_PATH"

# Use sed to replace the maxFeePerGas calculation
sed -i "s/const maxFeePerGas = baseFeePerGas.plus(neededPriority)/const maxFeePerGas = baseFeePerGas.times(2).plus(maxPriorityFeePerGas)/" "$FILE_PATH"

# Restart services
supervisorctl restart lamassu-server lamassu-admin-server

echo "All done!"
